function(define_tracked_option)
    # usage: define_tracked_option(<option_name> DEFAULT <default_value> [BOOL|STRING] DESCRIPTION <description of option> [ADVANCED]) 
    set(options ADVANCED BOOL STRING)
    set(oneValArgs DEFAULT DESCRIPTION)
    cmake_parse_arguments(DTO "${options}"  "${oneValArgs}" "" ${ARGN})

    list(LENGTH DTO_UNPARSED_ARGUMENTS num_unparsed)

    if(NOT (${num_unparsed} EQUAL 1))
        message(STATUS "${num_unparsed} ${ARGN}")
        message(FATAL_ERROR "define_tracked_option: bad number of arguments")
    endif()


    set(DTO_NAME "${DTO_UNPARSED_ARGUMENTS}")

    if("${DTO_DESCRIPTION}" STREQUAL "")
        set(DTO_DESCRIPTION "${DTO_NAME}")
    endif()

    if(${DTO_STRING})
        set(${DTO_NAME} ${DTO_DEFAULT} CACHE STRING "${DTO_DESCRIPTION}")
    elseif(${DTO_BOOL})
        set(${DTO_NAME} ${DTO_DEFAULT} CACHE BOOL "${DTO_DESCRIPTION}")
    else()
        message(FATAL_ERROR "define_tracked_option: must define option type")
    endif()

    if(${DTO_ADVANCED})
        mark_as_advanced(${DTO_NAME})
    endif()

    if(COMPILED_OPTIONS_LIST)
        set(COMPILED_OPTIONS_LIST "${COMPILED_OPTIONS_LIST}" "${DTO_NAME}=${${DTO_NAME}}" PARENT_SCOPE)
    else()
        set(COMPILED_OPTIONS_LIST "${DTO_NAME}=${${DTO_NAME}}" PARENT_SCOPE)
    endif()

    if (NOT "${DTO_DEFAULT}" STREQUAL "${${DTO_NAME}}")
        if(COMPILED_OPTIONS_LIST_NONDEFAULT)
            set(COMPILED_OPTIONS_LIST_NONDEFAULT "${COMPILED_OPTIONS_LIST_NONDEFAULT}" "${DTO_NAME}=${${DTO_NAME}}" PARENT_SCOPE)
        else()
            set(COMPILED_OPTIONS_LIST_NONDEFAULT "${DTO_NAME}=${${DTO_NAME}}" PARENT_SCOPE)
        endif()
    endif()
endfunction()


define_tracked_option(OPT_CUDA DEFAULT ON BOOL DESCRIPTION "Enable CUDA support")
define_tracked_option(OPT_MPI DEFAULT OFF BOOL DESCRIPTION "Enable MPI support")
define_tracked_option(OPT_PYTHON DEFAULT ON BOOL DESCRIPTION "Enable Python bindings")
define_tracked_option(OPT_VMD DEFAULT ON BOOL DESCRIPTION "Build LM plugin for VMD")

define_tracked_option(MPD_BOUNDARY_PERIODIC DEFAULT ON BOOL ADVANCED)
define_tracked_option(MPD_CUDA_3D_GRID_LAUNCH DEFAULT ON BOOL ADVANCED)
define_tracked_option(MPD_EXTRA_SANITY_CHECKS DEFAULT OFF BOOL ADVANCED)
define_tracked_option(MPD_FREAKYFAST DEFAULT ON BOOL ADVANCED)
define_tracked_option(MPD_GLOBAL_R_MATRIX DEFAULT ON BOOL ADVANCED)
define_tracked_option(MPD_GLOBAL_S_MATRIX DEFAULT ON BOOL ADVANCED)
define_tracked_option(MPD_GLOBAL_T_MATRIX DEFAULT ON BOOL ADVANCED)
define_tracked_option(MPD_LATTICE_MAX_OCCUPANCY DEFAULT 16 STRING DESCRIPTION "Maximum particles per lattice subvolume" ADVANCED)
define_tracked_option(MPD_MAPPED_OVERFLOWS DEFAULT ON BOOL ADVANCED)
define_tracked_option(MPD_MAX_REACTION_TABLE_ENTRIES DEFAULT 16384 STRING ADVANCED)
define_tracked_option(MPD_MAX_RL_MATRIX_ENTRIES DEFAULT 16384 STRING ADVANCED)
define_tracked_option(MPD_MAX_S_MATRIX_ENTRIES DEFAULT 16384 STRING ADVANCED)
define_tracked_option(MPD_MAX_TRANSITION_TABLE_ENTRIES DEFAULT 1048576 STRING ADVANCED)
define_tracked_option(MPD_NUMA_SUPPORT DEFAULT OFF BOOL ADVANCED)

define_tracked_option(RNG_CUDA_DOUBLE_PRECISION DEFAULT ON BOOL ADVANCED)
define_tracked_option(RNG_TUNE_XORWOW_BLOCK_SIZE DEFAULT 64 STRING ADVANCED)
define_tracked_option(RNG_TUNE_XORWOW_GRID_SIZE DEFAULT 64 STRING ADVANCED)
define_tracked_option(RNG_TUNE_XORWOW_THREAD_ITERATIONS DEFAULT 256 STRING ADVANCED)

define_tracked_option(PROF_CUDA_ENABLE DEFAULT OFF BOOL ADVANCED)
define_tracked_option(PROF_ENABLE DEFAULT OFF BOOL ADVANCED)
define_tracked_option(PROF_MAX_EVENTS DEFAULT 1000 STRING ADVANCED)
define_tracked_option(PROF_MAX_THREADS DEFAULT 8 STRING ADVANCED)
define_tracked_option(PROF_OUT_FILE DEFAULT "prof.out" STRING ADVANCED)
define_tracked_option(PROF_USE_CUEVENT DEFAULT ON BOOL ADVANCED)
define_tracked_option(PROF_USE_NVTX DEFAULT ON BOOL ADVANCED)

define_tracked_option(TUNE_FIRST_PASSAGE_TIME_BUFFER_SIZE DEFAULT 1000 STRING ADVANCED)
define_tracked_option(TUNE_LATTICE_BUILDER_WRITE_BUFFER_SIZE DEFAULT 1000 STRING DESCRIPTION "The number of objects the lattice builder will buffer before writing them to the file." ADVANCED)
define_tracked_option(TUNE_LATTICE_GZIP_CHUNK_SIZE DEFAULT 16 STRING DESCRIPTION "The chunk size to use when writing gzipped lattice frames." ADVANCED)
define_tracked_option(TUNE_LATTICE_GZIP_COMPRESSION_LEVEL DEFAULT 1 STRING DESCRIPTION "The compression level used for gzip when writing out the lattice frames. 1=lowest, 9=highest." ADVANCED)
define_tracked_option(TUNE_LOCAL_RNG_CACHE_SIZE DEFAULT 2048 STRING ADVANCED)
define_tracked_option(TUNE_MPD_MAX_OVERFLOW_REPLACEMENT_DIST DEFAULT 4 STRING DESCRIPTION "Parameters for the reaction kernel thread block size." ADVANCED)
define_tracked_option(TUNE_MPD_MAX_PARTICLE_OVERFLOWS DEFAULT 2048 STRING DESCRIPTION "Parameters for the reaction kernel thread block size." ADVANCED)
define_tracked_option(TUNE_MPD_REACTION_BLOCK_X_SIZE DEFAULT 32 STRING DESCRIPTION "Parameters for the reaction kernel thread block size." ADVANCED)
define_tracked_option(TUNE_MPD_REACTION_BLOCK_Y_SIZE DEFAULT 8 STRING DESCRIPTION "Parameters for the reaction kernel thread block size." ADVANCED)
define_tracked_option(TUNE_MPD_X_BLOCK_MAX_X_SIZE DEFAULT 256 STRING DESCRIPTION "Tuning parameters for the MpdRdmeSolver." ADVANCED)
define_tracked_option(TUNE_MPD_Y_BLOCK_X_SIZE DEFAULT 32 STRING DESCRIPTION "Tuning parameters for the MpdRdmeSolver." ADVANCED)
define_tracked_option(TUNE_MPD_Y_BLOCK_Y_SIZE DEFAULT 8 STRING DESCRIPTION "Tuning parameters for the MpdRdmeSolver." ADVANCED)
define_tracked_option(TUNE_MPD_Z_BLOCK_X_SIZE DEFAULT 32 STRING DESCRIPTION "Tuning parameters for the MpdRdmeSolver." ADVANCED)
define_tracked_option(TUNE_MPD_Z_BLOCK_Z_SIZE DEFAULT 8 STRING DESCRIPTION "Tuning parameters for the MpdRdmeSolver." ADVANCED)
define_tracked_option(TUNE_NRM_REUSE_PROPENSITIES DEFAULT ON BOOL DESCRIPTION "The next reaction method CME sampler can reuse existing propensities for dependent reaction changes, but in some cases it may be faster to just generate a new random number." ADVANCED)
define_tracked_option(TUNE_PARAMETER_VALUES_BUFFER_SIZE DEFAULT 1000 STRING ADVANCED)
define_tracked_option(TUNE_SPATIAL_MODEL_OBJECT_READ_BUFFER_SIZE DEFAULT 1000 STRING DESCRIPTION "The number of objects in the spatial model that will be read from the file in one read operation." ADVANCED)
define_tracked_option(TUNE_SPECIES_COUNTS_BUFFER_SIZE DEFAULT 1000 STRING ADVANCED)
